import { ReactNode } from 'react'; import { Moon,Sun } from 'lucide-react'; import { formatCompactNumber,formatCurrency } from '../../utils/format'; import { CurrencyCode,OrderItem } from '../../types';
import { Button } from './Button'; import { Card } from './Card'; import { SectionLoading } from './States';
export * from './utils'; export * from './Button'; export * from './Form'; export * from './Card'; export * from './Badge'; export * from './Modal'; export * from './Drawer'; export * from './States'; export * from './Table'; export * from './Toast';
export const PageHeader=({title,description,action}:{title:string;description:string;action?:ReactNode})=><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-medium text-emerald-700 dark:text-emerald-300">Tapro</p><h1 className="mt-2 text-[length:var(--text-page-title)] font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></div>{action&&<div className="flex flex-wrap gap-2">{action}</div>}</div>;
export const StatCard=({label,value,helper,tone='blue'}:{label:string;value:string|number;helper:string;tone?:'emerald'|'blue'|'amber'|'rose'})=><Card><p className="text-xs font-medium text-slate-500">{label}</p><div className="mt-4 text-3xl font-semibold">{typeof value==='number'?formatCompactNumber(value):value}</div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{helper}</p></Card>;
export const LoadingBlock=({label='Loading workspace...'}:{label?:string})=><SectionLoading label={label}/>;
export const ThemeToggle=({darkMode,onToggle}:{darkMode:boolean;onToggle:()=>void})=><Button variant="ghost" size="icon" onClick={onToggle} aria-label={darkMode?'Use light theme':'Use dark theme'}>{darkMode?<Sun aria-hidden className="h-4 w-4"/>:<Moon aria-hidden className="h-4 w-4"/>}</Button>;
export const DataTable=<T,>({columns,rows}:{columns:Array<{key:string;label:string;render:(row:T)=>ReactNode}>;rows:T[]})=><div className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-900"><tr>{columns.map(c=><th key={c.key} className="px-4 py-3 text-left text-xs font-semibold text-slate-500">{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-slate-100 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800">{columns.map(c=><td key={c.key} className="px-4 py-3 align-top text-slate-700 dark:text-slate-200">{c.render(r)}</td>)}</tr>)}</tbody></table></div></div>;
export const OrderItemsList=({items,currencyCode='LKR',emptyLabel='No items available'}:{items?:Array<Pick<OrderItem,'id'|'itemName'|'quantity'|'price'|'subTotal'>>;currencyCode?:CurrencyCode;emptyLabel?:string})=>!items?.length?<p className="text-sm text-slate-500">{emptyLabel}</p>:<div className="space-y-2">{items.map((x,i)=><div key={x.id??i} className="text-sm"><span className="font-medium">{x.quantity} x {x.itemName}</span><span className="text-slate-500"> - {formatCurrency(typeof x.subTotal==='number'?x.subTotal:x.price,currencyCode)}</span></div>)}</div>;
