import { HTMLAttributes, MouseEvent, PropsWithChildren, useId } from 'react';
import { X } from 'lucide-react';
import { createPortal } from 'react-dom';
import { useDialogBehavior } from './dialog-utils';
import { classNames } from './utils';
export const ModalHeader=({children,className,...p}:PropsWithChildren<HTMLAttributes<HTMLDivElement>>)=><div {...p} className={classNames('flex items-start justify-between gap-4 border-b border-slate-200 px-4 py-4 dark:border-slate-700 sm:px-6',className)}>{children}</div>;
export const ModalBody=({children,className,...p}:PropsWithChildren<HTMLAttributes<HTMLDivElement>>)=><div {...p} className={classNames('min-h-0 overflow-y-auto px-4 py-5 sm:px-6',className)}>{children}</div>;
export const ModalFooter=({children,className,...p}:PropsWithChildren<HTMLAttributes<HTMLDivElement>>)=><div {...p} className={classNames('flex flex-wrap justify-end gap-2 border-t border-slate-200 px-4 py-4 pb-[max(1rem,env(safe-area-inset-bottom))] dark:border-slate-700 sm:px-6',className)}>{children}</div>;
export const Modal=({open,onClose,title,description,children,size='medium',closeOnOverlay=true}:PropsWithChildren<{open:boolean;onClose:()=>void;title:string;description?:string;size?:'small'|'medium'|'large'|'full';closeOnOverlay?:boolean}>)=>{const titleId=useId(),descId=useId();const ref=useDialogBehavior(open,onClose);if(!open)return null;const overlay=(e:MouseEvent)=>{if(closeOnOverlay&&e.target===e.currentTarget)onClose()};return createPortal(<div onMouseDown={overlay} className="fixed inset-0 z-[var(--z-modal)] flex items-center justify-center bg-slate-950/55 p-2 sm:p-4"><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description?descId:undefined} className={classNames('flex max-h-[calc(100dvh-1rem)] w-full flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900 sm:max-h-[calc(100dvh-2rem)]',size==='small'?'max-w-md':size==='medium'?'max-w-xl':size==='large'?'max-w-3xl':'max-w-6xl')}><ModalHeader><div><h2 id={titleId} className="text-lg font-semibold text-slate-950 dark:text-white">{title}</h2>{description&&<p id={descId} className="mt-1 text-sm text-slate-600 dark:text-slate-300">{description}</p>}</div><button aria-label="Close dialog" onClick={onClose} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X aria-hidden className="h-5 w-5"/></button></ModalHeader>{children}</div></div>,document.body)};
